version: 0.2

env:
  variables:
    AWS_S3_NAME: "digital-aws"
    AWS_S3_REGION: "sa-east-1"
phases:
  build:
    commands:
      - echo "Entered the build phase.."
  post_build:
    commands:
      - aws s3 sync ./swagger/ s3://AWS_S3_NAME --acl public-read --region AWS_S3_REGION
