version: '3.3'
services:
  swagger-ui:
    image: swaggerapi/api-ui:v3.23.3
    container_name: api-ui
    ports:
      - "8001:8080"
    volumes:
      - ./api:/usr/share/nginx/html/api
    environment:
      API_URL: api/api.yaml