version: '3.3'
services:
  swagger-ui:
    image: swaggerapi/swagger-ui:$(cat ./VERSION)
    container_name: digital-swagger
    ports:
      - "80:8080"
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      API_URL: swagger/api.yaml